# Generated by Django 2.0.3 on 2018-04-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_num', models.IntegerField()),
                ('street_name', models.CharField(max_length=64)),
                ('House_number', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dinner_platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platter_name', models.CharField(max_length=30)),
                ('platter_size', models.CharField(max_length=30)),
                ('platter_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone_num', models.IntegerField()),
                ('street_name', models.CharField(max_length=64)),
                ('House_number', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='pasta',
            fields=[
                ('pasta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pasta_name', models.CharField(max_length=30)),
                ('pasta_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('pizza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pizza_type', models.CharField(max_length=30)),
                ('pizza_size', models.CharField(max_length=64)),
                ('topping_number', models.IntegerField()),
                ('pizza_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('salad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salad_name', models.CharField(max_length=30)),
                ('salad_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('sub_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
                ('sub_size', models.CharField(max_length=30)),
                ('sub_extras', models.CharField(max_length=30)),
                ('sub_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product'),
        ),
    ]
