# Generated by Django 2.0.3 on 2018-04-12 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerid',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='House_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
