# Generated by Django 2.0.3 on 2018-04-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180412_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
