# Generated by Django 2.0.3 on 2018-04-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dinner_platter',
        ),
        migrations.DeleteModel(
            name='pasta',
        ),
        migrations.DeleteModel(
            name='pizza',
        ),
        migrations.DeleteModel(
            name='pizza_topping',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='sub',
        ),
    ]
