# Generated by Django 2.0.3 on 2018-04-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pizzatoppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatoppings',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
