# Generated by Django 2.0.3 on 2018-04-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180415_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
